spring.datasource.url=jdbc:postgresql://localhost:5432/techub
spring.datasource.username=techub_user
spring.datasource.password=techub_pass
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/docs

security.jwt.secret-key=yL9npj1a7tWuBgwZwMk+xbSHzXbmbIln/kb/Wc4LZbc=
security.jwt.expiration-time=3600000
server.port=8080
